# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160413_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_event', to='users.Event'),
        ),
        migrations.AlterField(
            model_name='profile_event',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_profile', to='users.Profile'),
        ),
    ]
