# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
