# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_dataset_publication', to='users.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_event_publication', to='users.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='event',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='url',
        ),
        migrations.AddField(
            model_name='publication_event',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_publication_event', to='users.Publication'),
        ),
        migrations.AddField(
            model_name='publication_dataset',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_publication_dataset', to='users.Publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='events',
            field=models.ManyToManyField(through='users.Publication_Event', to='users.Event'),
        ),
    ]
