# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule_event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='schedule_event',
            name='parent_schedule_event',
        ),
        migrations.AddField(
            model_name='schedule_event',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Program'),
        ),
    ]
