# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160512_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_event',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
