# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160530_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='event',
        ),
        migrations.RemoveField(
            model_name='schedule_event',
            name='program',
        ),
        migrations.AddField(
            model_name='schedule_event',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Event'),
        ),
        migrations.AddField(
            model_name='schedule_event',
            name='parent_schedule_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Schedule_Event'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
