# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 08:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160824_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='article',
        ),
        migrations.RemoveField(
            model_name='result',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='result',
            name='code',
        ),
        migrations.RemoveField(
            model_name='result',
            name='other',
        ),
        migrations.RemoveField(
            model_name='result',
            name='sheets',
        ),
        migrations.RemoveField(
            model_name='result',
            name='website',
        ),
        migrations.AddField(
            model_name='result',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Track'),
        ),
        migrations.AlterField(
            model_name='schedule_event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='result_user',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Result'),
        ),
    ]
