# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160829_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid_Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result_Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Track')),
            ],
        ),
        migrations.RemoveField(
            model_name='col',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='result',
            name='track',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='schedule_event',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Col',
        ),
        migrations.AddField(
            model_name='grid_header',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Result_Grid'),
        ),
        migrations.AddField(
            model_name='result',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Result_Grid'),
        ),
        migrations.AddField(
            model_name='submission',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Result_Grid'),
        ),
    ]
