# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160530_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='profile_event',
        ),
        migrations.AddField(
            model_name='profile_event',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role'),
        ),
        migrations.AlterField(
            model_name='event_partner',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role'),
        ),
    ]
