# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 20:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160904_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('publication', models.URLField(null=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Special_Issue')),
            ],
        ),
    ]
