# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 16:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160513_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
