# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_gallery_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_image',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
    ]
