# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='issue',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
