# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160429_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
