# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160912_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_issue_publication', to='users.Special_Issue'),
        ),
    ]
