# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160531_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_event',
            old_name='parent_schedule_event',
            new_name='schedule_event_parent',
        ),
        migrations.AlterField(
            model_name='gallery_image',
            name='image',
            field=models.ImageField(null=True, upload_to='workshop_gallery'),
        ),
    ]
