# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160519_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
