# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160531_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_partner',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Event'),
        ),
        migrations.AlterField(
            model_name='event_partner',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Partner'),
        ),
        migrations.AlterField(
            model_name='profile_event',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_event', to='users.Event'),
        ),
        migrations.AlterField(
            model_name='profile_event',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_profile', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='track',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Challenge'),
        ),
        migrations.AlterField(
            model_name='track',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Dataset'),
        ),
    ]
