# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_org',
            field=models.BooleanField(default=False),
        ),
    ]
