# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160430_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(null=True, upload_to=users.models.data_path),
        ),
        migrations.AlterField(
            model_name='member_partner',
            name='avatar',
            field=models.ImageField(null=True, upload_to=users.models.partner_member_avatar_path),
        ),
        migrations.AlterField(
            model_name='partner',
            name='banner',
            field=models.ImageField(null=True, upload_to=users.models.partner_avatar_path),
        ),
    ]
