# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_event_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_relation',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation', to='users.Event'),
        ),
        migrations.AlterField(
            model_name='event_relation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_associated', to='users.Event'),
        ),
    ]
