# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160430_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
