# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 20:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_chalearn_cimlbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event_relation',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
