# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160430_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_event',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='profile_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile_Event'),
        ),
    ]
