# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 16:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result_user',
            name='link',
        ),
        migrations.AddField(
            model_name='result_user',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='result_user',
            name='paper',
            field=models.FileField(null=True, upload_to=users.models.paper_path),
        ),
    ]
