# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160606_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_relation',
            old_name='event_associated',
            new_name='event',
        ),
    ]
