# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160413_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='description',
        ),
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.FileField(null=True, upload_to='data/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
