# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 21:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160929_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='sub_file',
        ),
        migrations.AddField(
            model_name='dataset',
            name='evaluation_file',
            field=models.FileField(null=True, upload_to=users.models.dataset_path),
        ),
        migrations.AddField(
            model_name='dataset',
            name='gt_file',
            field=models.FileField(null=True, upload_to=users.models.dataset_path),
        ),
        migrations.AddField(
            model_name='dataset',
            name='threshold',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='result_grid',
            name='instructions',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ground_truth',
            field=models.FileField(null=True, upload_to=users.models.gt_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.FileField(null=True, upload_to=users.models.output_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='prediction_file',
            field=models.FileField(null=True, upload_to=users.models.prediction_path),
        ),
    ]
