# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_schedule_event_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_event',
            old_name='dataset',
            new_name='dataset_schedule',
        ),
        migrations.RemoveField(
            model_name='schedule_event',
            name='event',
        ),
        migrations.AddField(
            model_name='schedule_event',
            name='event_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_program', to='users.Event'),
        ),
        migrations.AddField(
            model_name='schedule_event',
            name='event_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_schedule', to='users.Event'),
        ),
    ]
