# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20161002_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='threshold',
        ),
        migrations.AddField(
            model_name='result_grid',
            name='threshold',
            field=models.FloatField(null=True),
        ),
    ]
