# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 09:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20160607_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='metric',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='software',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
