# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 09:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160608_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='baseline',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='metrics',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
