# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20160423_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_path',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='userpics/'),
        ),
    ]
