# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 07:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160608_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=2, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
