# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('score', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='result',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='chalearn',
        ),
        migrations.RemoveField(
            model_name='event',
            name='chalearn',
        ),
        migrations.RemoveField(
            model_name='result',
            name='score',
        ),
        migrations.RemoveField(
            model_name='result',
            name='title',
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Chalearn',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='score',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Result'),
        ),
    ]
