# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_partner_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('bio', models.TextField(max_length=3000)),
                ('avatar', models.ImageField(null=True, upload_to='userpics/')),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='events',
            field=models.ManyToManyField(null=True, through='users.Challenge_Partner', to='users.Event'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='partner',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member_Partner'),
        ),
    ]
