# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20160614_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='dataset',
        ),
        migrations.AddField(
            model_name='result',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Challenge'),
        ),
    ]
