# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20160614_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Result'),
        ),
    ]
