# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20160614_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='/static/images/default.jpg', null=True, upload_to=users.models.partner_member_avatar_path),
        ),
        migrations.AlterField(
            model_name='gallery_image',
            name='image',
            field=models.ImageField(null=True, upload_to='workshop_gallery'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='banner',
            field=models.ImageField(null=True, upload_to=users.models.partner_avatar_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/images/default.jpg', null=True, upload_to=users.models.user_avatar_path),
        ),
    ]
