# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20160620_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='publication_ref',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_code',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='sub_file',
            field=models.FileField(null=True, upload_to=users.models.submission_path),
        ),
    ]
