# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20160620_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='publication_ref',
            new_name='publication',
        ),
    ]
