# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20160621_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_dataset',
            name='dataset1',
        ),
        migrations.AddField(
            model_name='profile_dataset',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_dataset_profile', to='users.Dataset'),
        ),
        migrations.AlterField(
            model_name='profile_dataset',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_profile_dataset', to='users.Profile'),
        ),
    ]
