from django.urls import re_path, path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserRegisterForm, UserLoginForm, ChangePassForm, ResetPassForm, SetPassForm, MemberCreationForm
from registration.backends.default.views import RegistrationView, ActivationView
from django.views.generic.base import TemplateView

urlpatterns = [
    re_path(r'^home/$', views.home, name="home"),
    re_path(r'^home-edit/$', views.home_edit, name="home_edit"),
    re_path(r'^help/$', views.help, name="help"),
    re_path(r'^help-edit/$', views.help_edit, name="help_edit"),
    re_path(r'^cimlbook/(?P<id>\d+)/$', views.cimlbook_detail, name="cimlbook_detail"),
    re_path(r'^cimlbook/(?P<id>\d+)/edit/$', views.cimlbook_edit, name="cimlbook_edit"),
    re_path(r'^cimlbook/(?P<id>\d+)/remove/$', views.cimlbook_remove, name="cimlbook_remove"),
    re_path(r'^cimlbook/creation/$', views.cimlbook_creation, name="cimlbook_creation"),
    re_path(r'^main-organizers/$', views.main_organizers, name="main_organizers"),
    # Register, Login, edit password urls (Django auth)
    re_path(r'^register/$', RegistrationView.as_view(form_class=UserRegisterForm), name='register'),
    re_path(r'^login/$', auth_views.LoginView.as_view(authentication_form=UserLoginForm), name='auth_login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(next_page='home'), name='auth_logout'),
    re_path(r'^password/change/$', auth_views.PasswordChangeView.as_view(form_class=ChangePassForm), name='auth_password_change'),
    re_path(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='auth_password_reset'),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='auth_password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'^activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'), name='registration_activation_complete'),
    re_path(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    re_path(r'^register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    re_path(r'^register/closed/$', TemplateView.as_view(template_name='registration/registration_closed.html'), name='registration_disallowed'),
    # User urls
    re_path(r'^user/list/$', views.user_list, name="user_list"),
    re_path(r'^user/edit/(?P<id>\d+)/$', views.user_edit, name="user_edit"),
    re_path(r'^user/export-csv/$', views.export_user_csv, name="export_user_csv"),
    re_path(r'^user/export-xls/$', views.export_user_xls, name="export_user_xls"),
    re_path(r'^user/export-xlsx/$', views.export_user_xlsx, name="export_user_xlsx"),
    # Profile urls (Editors, Organizers...)
    re_path(r'^profile/edit/(?P<member_id>\d+)/$', views.profile_edit, name="profile_edit"),
    # url(r'^profile/creation/$', views.Backend.as_view(form_class = MemberCreationForm,template_name='registration/registration_form_email.html'), name="profile_creation"),
    re_path(r'^event/(?P<id>\d+)/people/creation/$', views.profile_creation, name="event_profile_creation"),
    # Dataset urls
    re_path(r'^dataset/list/$', views.dataset_list, name="dataset_list"),
    re_path(r'^dataset/creation/$', views.dataset_creation, name="dataset_creation"),
    # url(r'^dataset/(?P<id>\d+)/edit/$', views.dataset_edit, name="dataset_edit"),
    re_path(r'^dataset/(?P<id>\d+)/edit/description$', views.dataset_edit_desc, name="dataset_edit_desc"),
    # url(r'^dataset/(?P<id>\d+)/edit/schedule$', views.dataset_edit_schedule, name="dataset_edit_schedule"),
    re_path(r'^dataset/(?P<id>\d+)/edit/associated-events$', views.dataset_edit_relations, name="dataset_edit_relations"),
    re_path(r'^dataset/(?P<id>\d+)/edit/datas$', views.dataset_edit_datas, name="dataset_edit_datas"),
    re_path(r'^dataset/(?P<id>\d+)/edit/results/(?P<grid_id>\d+)/$', views.dataset_edit_results, name="dataset_edit_results"),
    re_path(r'^dataset/(?P<id>\d+)/edit/news$', views.dataset_edit_news, name="dataset_edit_news"),
    re_path(r'^dataset/(?P<id>\d+)/edit/publications$', views.dataset_edit_publications, name="dataset_edit_publications"),
    # url(r'^dataset/(?P<id>\d+)/edit/(?P<col_id>\d+)/column$', views.dataset_edit_col, name="dataset_edit_col"),
    re_path(r'^dataset/(?P<id>\d+)/edit/(?P<submission_id>\d+)/submission$', views.dataset_edit_submission, name="dataset_edit_submission"),
    re_path(r'^dataset/(?P<id>\d+)/remove/(?P<submission_id>\d+)/submission$', views.dataset_remove_submission, name="dataset_remove_submission"),
    re_path(r'^dataset/(?P<id>\d+)/edit/members$', views.dataset_edit_members, name="dataset_edit_members"),
    re_path(r'^dataset/(?P<id>\d+)/publish/$', views.dataset_publish, name="dataset_publish"),
    re_path(r'^dataset/(?P<id>\d+)/unpublish/$', views.dataset_unpublish, name="dataset_unpublish"),
    re_path(r'^dataset/(?P<id>\d+)/description/$', views.dataset_desc, name="dataset_desc"),
    # url(r'^dataset/(?P<id>\d+)/schedule/$', views.dataset_schedule, name="dataset_schedule"),
    re_path(r'^dataset/(?P<id>\d+)/publications/$', views.dataset_publications, name="dataset_publications"),
    re_path(r'^dataset/(?P<id>\d+)/remove/$', views.dataset_remove, name="dataset_remove"),
    # url(r'^dataset/select/(?P<id>\d+)/$', views.dataset_select, name="dataset_select"),
    # Data urls
    re_path(r'^dataset/(?P<id>\d+)/data/creation/$', views.data_creation, name="data_creation"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/remove/$', views.data_remove, name="data_remove"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/description/$', views.data_desc, name="data_desc"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/software/$', views.data_software, name="data_software"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/files/$', views.data_files, name="data_files"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/metric/$', views.data_metric, name="data_metric"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/results/(?P<grid_id>\d+)/$', views.dataset_results, name="dataset_results"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/results/fact-sheet/(?P<f_sheet_id>\d+)/$', views.result_fact_sheet, name="dataset_result_fact_sheet"),
    # url(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/edit/$', views.data_edit, name="data_edit"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/edit/description$', views.data_edit_desc, name="data_edit_desc"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/edit/files$', views.data_edit_files, name="data_edit_files"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/file/creation/$', views.file_creation, name="file_creation"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/file/(?P<file_id>\d+)/remove/$', views.file_remove, name="file_remove"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/publish/$', views.data_publish, name="data_publish"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/data/(?P<id>\d+)/unpublish/$', views.data_unpublish, name="data_unpublish"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/schedule/creation$', views.schedule_creation, name="schedule_creation"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/schedule/(?P<schedule_id>\d+)/edit/$', views.schedule_edit, name="schedule_edit"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/schedule/(?P<schedule_id>\d+)/remove/$', views.dataset_schedule_remove, name="dataset_schedule_remove"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/associated-events/creation$', views.event_relation_creation, name="dataset_associated_events_creation"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/associated-events/(?P<relation_id>\d+)/remove$', views.event_relation_remove, name="dataset_associated_events_remove"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/associated-events/$', views.dataset_associated_events, name="dataset_associated_events"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/news/creation/$', views.news_creation, name="dataset_news_creation"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/news/(?P<news_id>\d+)/remove$', views.dataset_news_remove, name="dataset_news_remove"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/news/(?P<news_id>\d+)/edit/$', views.news_edit, name="dataset_news_edit"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/submission/(?P<grid_id>\d+)/creation$', views.submission_creation, name="submission_creation"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/submission/(?P<grid_id>\d+)/instructions/edit/$', views.submission_instructions_edit, name="submission_instructions_edit"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/submission/(?P<sub_id>\d+)/score/$', views.submission_score, name="submission_score"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/submission/(?P<sub_id>\d+)/resume/$', views.result_user_submission, name="submission_resume"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/submission/(?P<sub_id>\d+)/fact-sheet/creation/$', views.result_user_submission_edit, name="submission_fact_sheet_creation"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/submission/(?P<sub_id>\d+)/fact-sheet/(?P<sheet_id>\d+)/edit/$', views.result_user_submission_edit, name="submission_fact_sheet_edit"),
    # re_path(r'^dataset/(?P<dataset_id>\d+)/submission/(?P<sub_id>\d+)/(?P<grid_id>\d+)/score/$', views.submission_score, name="submission_score"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/member/select/$', views.dataset_profile_select, name="dataset_profile_select"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/member/(?P<member_id>\d+)/remove$', views.dataset_member_remove, name="dataset_member_remove"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/results/(?P<grid_id>\d+)/export-participants-csv/$', views.export_participants_csv, name="export_participants_csv"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/results/(?P<grid_id>\d+)/export-submitted-xls/$', views.export_participants_xls, name="export_participants_xls"),
    re_path(r'^dataset/(?P<dataset_id>\d+)/results/(?P<grid_id>\d+)/export-submitted-xlsx/$', views.export_participants_xlsx, name="export_participants_xlsx"),
    re_path(r'^dataset/(?P<id>\d+)/publication/creation/$', views.publication_creation, name="dataset_publication_creation"),
    re_path(r'^dataset/(?P<id>\d+)/publication/(?P<pub_id>\d+)/edit/$', views.publication_edit, name="publication_edit"),
    re_path(r'^dataset/(?P<id>\d+)/publication/(?P<pub_id>\d+)/remove/$', views.publication_remove, name="publication_remove"),
    # Partner urls
    re_path(r'^sponsors/list/$', views.partner_list, name="partners_list"),
    re_path(r'^sponsors/creation/$', views.partner_creation, name="general_partner_creation"),
    re_path(r'^event/(?P<id>\d+)/sponsors/creation/$', views.partner_creation, name="partner_creation"),
    re_path(r'^event/(?P<id>\d+)/sponsors/select/$', views.partner_select, name="partner_select"),
    # Event urls
    re_path(r'^event/list/$', views.event_list, name="event_list"),
    re_path(r'^event/creation/$', views.event_creation, name="event_creation"),
    re_path(r'^event/(?P<id>\d+)/detail/$', views.event_detail, name="event_detail"),
    re_path(r'^event/(?P<id>\d+)/edit//$', views.event_edit, name="event_edit"),
    re_path(r'^event/(?P<id>\d+)/remove/$', views.event_remove, name="event_remove"),
    re_path(r'^event/(?P<event_id>\d+)/export-members-csv/$', views.export_members_csv, name="export_members_csv"),
    re_path(r'^event/(?P<event_id>\d+)/export-members-xls/$', views.export_members_xls, name="export_members_xls"),
    re_path(r'^event/(?P<event_id>\d+)/export-members-xlsx/$', views.export_members_xlsx, name="export_members_xlsx"),
    # re_path(r'^event/(?P<event_id>\d+)/program/(?P<program_id>\d+)/subevent/creation/$', views.subevent_creation, name="subevent_creation"),
    # Challenge urls
    re_path(r'^challenge/(?P<id>\d+)/publish/$', views.challenge_publish, name="challenge_publish"),
    re_path(r'^challenge/(?P<id>\d+)/unpublish/$', views.challenge_unpublish, name="challenge_unpublish"),
    re_path(r'^challenge/(?P<id>\d+)/edit/description$', views.challenge_edit_desc, name="challenge_edit_desc"),
    re_path(r'^challenge/(?P<id>\d+)/edit/schedule$', views.challenge_edit_schedule, name="challenge_edit_schedule"),
    re_path(r'^challenge/(?P<id>\d+)/edit/associated-events$', views.challenge_edit_relation, name="challenge_edit_relation"),
    re_path(r'^challenge/(?P<id>\d+)/edit/people$', views.challenge_edit_members, name="challenge_edit_members"),
    re_path(r'^challenge/(?P<id>\d+)/edit/sponsors$', views.challenge_edit_sponsors, name="challenge_edit_sponsors"),
    re_path(r'^challenge/(?P<id>\d+)/edit/tracks$', views.challenge_edit_tracks, name="challenge_edit_tracks"),
    re_path(r'^challenge/(?P<id>\d+)/edit/news$', views.challenge_edit_news, name="challenge_edit_news"),
    re_path(r'^challenge/(?P<id>\d+)/edit/publications$', views.challenge_edit_publications, name="challenge_edit_publications"),
    re_path(r'^challenge/(?P<id>\d+)/description/$', views.challenge_desc, name="challenge_desc"),
    re_path(r'^challenge/(?P<id>\d+)/people/(?P<role_id>\d+)/$', views.challenge_members, name="challenge_members"),
    re_path(r'^challenge/(?P<id>\d+)/sponsors/$', views.challenge_sponsors, name="challenge_sponsors"),
    re_path(r'^challenge/(?P<id>\d+)/sponsors/creation/$', views.challenge_sponsors_creation, name="challenge_sponsors_creation"),
    re_path(r'^challenge/(?P<id>\d+)/sponsors/(?P<sponsor_id>\d+)/remove$', views.event_partner_remove, name="challenge_partner_remove"),
    re_path(r'^challenge/(?P<id>\d+)/schedule/$', views.challenge_schedule, name="challenge_schedule"),
    re_path(r'^challenge/(?P<id>\d+)/schedule/(?P<program_id>\d+)/remove$', views.event_schedule_remove, name="challenge_schedule_remove"),
    re_path(r'^challenge/(?P<id>\d+)/schedule/(?P<schedule_id>\d+)/edit/$', views.schedule_edit, name="challenge_schedule_edit"),
    re_path(r'^challenge/(?P<id>\d+)/schedule/creation$', views.schedule_creation, name="challenge_schedule_creation"),
    re_path(r'^challenge/(?P<id>\d+)/publications/$', views.challenge_publications, name="challenge_publications"),
    re_path(r'^challenge/(?P<id>\d+)/associated-events/$', views.challenge_associated_events, name="challenge_associated_events"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/remove$', views.track_remove, name="track_remove"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/description/$', views.track_desc, name="track_desc"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/metrics/$', views.track_metrics, name="track_metrics"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/baseline/$', views.track_baseline, name="track_baseline"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/$', views.track_result, name="track_result"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/(?P<result_id>\d+)/edit/$', views.result_edit, name="result_edit"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/(?P<result_id>\d+)/fact-sheet/(?P<sheet_id>\d+)/edit/$', views.fact_sheet_creation, name="fact_sheet_edit"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/(?P<result_id>\d+)/fact-sheet/creation/$', views.fact_sheet_creation, name="fact_sheet_creation"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/fact-sheet/(?P<f_sheet_id>\d+)/$', views.result_fact_sheet, name="result_fact_sheet"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/(?P<result_id>\d+)/remove/$', views.result_remove, name="result_remove"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/header/(?P<header_id>\d+)/edit/$', views.header_edit, name="header_edit"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/new-table/$', views.result_new_table, name="result_new_table"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/result/new-row/$', views.result_new_row, name="result_new_row"),
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/edit/description/$', views.track_edit_desc, name="track_edit_desc"),    
    re_path(r'^challenge/(?P<id>\d+)/track/(?P<track_id>\d+)/edit/result/$', views.track_edit_result, name="track_edit_result"),
    re_path(r'^challenge/(?P<id>\d+)/track/creation/$', views.track_creation, name="track_creation"),
    re_path(r'^challenge/(?P<id>\d+)/publication/creation/$', views.publication_creation, name="challenge_publication_creation"),
    re_path(r'^challenge/(?P<id>\d+)/publication/(?P<pub_id>\d+)/edit/$', views.publication_edit, name="publication_edit"),
    re_path(r'^challenge/(?P<id>\d+)/publication/(?P<pub_id>\d+)/remove/$', views.publication_remove, name="publication_remove"),
    re_path(r'^challenge/(?P<id>\d+)/associated-events/creation$', views.event_relation_creation, name="challenge_relation_creation"),
    re_path(r'^challenge/(?P<id>\d+)/associated-events/(?P<relation_id>\d+)/remove$', views.event_relation_remove, name="challenge_relation_remove"),
    # re_path(r'^challenge/(?P<id>\d+)/associated-events/(?P<relation_id>\d+)/edit$', views.event_relation_edit, name="challenge_relation_edit"),
    re_path(r'^challenge/(?P<id>\d+)/people/select/$', views.profile_select, name="challenge_profile_select"),
    re_path(r'^challenge/(?P<id>\d+)/people/(?P<member_id>\d+)/remove$', views.event_member_remove, name="challenge_member_remove"),
    re_path(r'^challenge/(?P<id>\d+)/people/(?P<member_id>\d+)/edit/$', views.profile_edit, name="challenge_profile_edit"),
    # re_path(r'^challenge/(?P<id>\d+)/people/creation/$', views.profile_creation, name="challenge_profile_creation"),
    re_path(r'^challenge/(?P<id>\d+)/news/creation/$', views.news_creation, name="challenge_news_creation"),
    re_path(r'^challenge/(?P<id>\d+)/news/(?P<news_id>\d+)/edit/$', views.news_edit, name="challenge_news_edit"),
    re_path(r'^challenge/(?P<id>\d+)/news/(?P<news_id>\d+)/remove$', views.event_news_remove, name="challenge_news_remove"),
    # Workshop urls
    re_path(r'^workshop/(?P<id>\d+)/publish/$', views.workshop_publish, name="workshop_publish"),
    re_path(r'^workshop/(?P<id>\d+)/unpublish/$', views.workshop_unpublish, name="workshop_unpublish"),
    # re_path(r'^workshop/(?P<id>\d+)/edit/$', views.workshop_edit, name="workshop_edit"),
    re_path(r'^workshop/(?P<id>\d+)/edit/description$', views.workshop_edit_desc, name="workshop_edit_desc"),
    re_path(r'^workshop/(?P<id>\d+)/edit/schedule$', views.workshop_edit_schedule, name="workshop_edit_schedule"),
    re_path(r'^workshop/(?P<id>\d+)/edit/associated-events$', views.workshop_edit_relations, name="workshop_edit_relations"),
    re_path(r'^workshop/(?P<id>\d+)/edit/program$', views.workshop_edit_program, name="workshop_edit_program"),
    re_path(r'^workshop/(?P<id>\d+)/edit/people$', views.workshop_edit_members, name="workshop_edit_members"),
    re_path(r'^workshop/(?P<id>\d+)/edit/gallery$', views.workshop_edit_gallery, name="workshop_edit_gallery"),
    re_path(r'^workshop/(?P<id>\d+)/edit/news$', views.workshop_edit_news, name="workshop_edit_news"),
    re_path(r'^workshop/(?P<id>\d+)/edit/publications$', views.workshop_edit_publications, name="workshop_edit_publications"),
    re_path(r'^workshop/(?P<id>\d+)/description/$', views.workshop_desc, name="workshop_desc"),
    re_path(r'^workshop/(?P<id>\d+)/program/$', views.workshop_program, name="workshop_program"),
    re_path(r'^workshop/(?P<id>\d+)/program/(?P<program_id>\d+)/remove$', views.workshop_program_remove, name="workshop_program_remove"),
    re_path(r'^workshop/(?P<id>\d+)/program/creation/$', views.program_creation, name="program_creation"),
    re_path(r'^workshop/(?P<id>\d+)/program/(?P<program_id>\d+)/edit/$', views.schedule_edit, name="program_edit"),
    re_path(r'^workshop/(?P<id>\d+)/schedule/$', views.workshop_schedule, name="workshop_schedule"),
    re_path(r'^workshop/(?P<id>\d+)/schedule/(?P<program_id>\d+)/remove$', views.event_schedule_remove, name="workshop_schedule_remove"),
    re_path(r'^workshop/(?P<id>\d+)/schedule/(?P<schedule_id>\d+)/edit/$', views.schedule_edit, name="workshop_schedule_edit"),
    re_path(r'^workshop/(?P<id>\d+)/schedule/creation$', views.schedule_creation, name="workshop_schedule_creation"),
    re_path(r'^workshop/(?P<id>\d+)/associated-events/$', views.workshop_associated_events, name="workshop_associated_events"),
    re_path(r'^workshop/(?P<id>\d+)/people/(?P<role_id>\d+)/$', views.workshop_members, name="workshop_members"),
    re_path(r'^workshop/(?P<id>\d+)/publications/$', views.workshop_publications, name="workshop_publications"),
    re_path(r'^workshop/(?P<id>\d+)/gallery/$', views.workshop_gallery, name="workshop_gallery"),
    re_path(r'^workshop/(?P<id>\d+)/gallery/add$', views.add_gallery_picture, name="add_gallery_picture"),
    re_path(r'^workshop/(?P<id>\d+)/gallery-picture/(?P<pic_id>\d+)/remove$', views.remove_gallery_picture, name="remove_gallery_picture"),
    re_path(r'^workshop/(?P<id>\d+)/gallery-picture/(?P<pic_id>\d+)/edit$', views.edit_gallery_picture, name="edit_gallery_picture"),
    re_path(r'^workshop/(?P<id>\d+)/gallery-picture/remove/$', views.remove_gallery, name="remove_gallery"),
    re_path(r'^workshop/(?P<id>\d+)/publication/creation/$', views.publication_creation, name="workshop_publication_creation"),
    re_path(r'^workshop/(?P<id>\d+)/publication/(?P<pub_id>\d+)/edit/$', views.publication_edit, name="publication_edit"),
    re_path(r'^workshop/(?P<id>\d+)/publication/(?P<pub_id>\d+)/remove/$', views.publication_remove, name="publication_remove"),
    re_path(r'^workshop/(?P<id>\d+)/sponsors/$', views.workshop_sponsors, name="workshop_sponsors"),
    re_path(r'^workshop/(?P<id>\d+)/edit/sponsors$', views.workshop_edit_sponsors, name="workshop_edit_sponsors"),
    re_path(r'^workshop/(?P<id>\d+)/sponsors/creation/$', views.workshop_sponsors_creation, name="workshop_sponsors_creation"),
    re_path(r'^workshop/(?P<id>\d+)/sponsors/(?P<sponsor_id>\d+)/remove$', views.event_partner_remove, name="workshop_partner_remove"),
    re_path(r'^workshop/(?P<id>\d+)/associated-events/creation$', views.event_relation_creation, name="workshop_relation_creation"),
    re_path(r'^workshop/(?P<id>\d+)/associated-events/(?P<relation_id>\d+)/remove$', views.event_relation_remove, name="workshop_relation_remove"),
    # re_path(r'^workshop/(?P<id>\d+)/associated-events/(?P<relation_id>\d+)/edit$', views.event_relation_edit, name="workshop_relation_edit"),
    # re_path(r'^workshop/(?P<id>\d+)/people/creation$', views.speaker_creation, name="speaker_creation"),
    re_path(r'^workshop/(?P<id>\d+)/people/select$', views.profile_select, name="workshop_profile_select"),
    re_path(r'^workshop/(?P<id>\d+)/people/(?P<member_id>\d+)/remove$', views.event_member_remove, name="workshop_member_remove"),
    re_path(r'^workshop/(?P<id>\d+)/people/(?P<member_id>\d+)/edit/$', views.profile_edit, name="workshop_profile_edit"),
    re_path(r'^workshop/(?P<id>\d+)/news/creation/$', views.news_creation, name="workshop_news_creation"),
    re_path(r'^workshop/(?P<id>\d+)/news/(?P<news_id>\d+)/edit/$', views.news_edit, name="workshop_news_edit"),
    re_path(r'^workshop/(?P<id>\d+)/news/(?P<news_id>\d+)/remove$', views.event_news_remove, name="workshop_news_remove"),
    # Special issues urls
    re_path(r'^special-issue/(?P<id>\d+)/publish/$', views.special_issue_publish, name="special_issue_publish"),
    re_path(r'^special-issue/(?P<id>\d+)/unpublish/$', views.special_issue_unpublish, name="special_issue_unpublish"),
    # re_path(r'^special-issue/(?P<id>\d+)/edit/$', views.special_issue_edit, name="special_issue_edit"),
    re_path(r'^special-issue/(?P<id>\d+)/edit/description$', views.special_issue_edit_desc, name="special_issue_edit_desc"),
    re_path(r'^special-issue/(?P<id>\d+)/edit/associated-events$', views.special_issue_edit_relations, name="special_issue_edit_relations"),
    re_path(r'^special-issue/(?P<id>\d+)/edit/schedule$', views.special_issue_edit_schedule, name="special_issue_edit_schedule"),
    re_path(r'^special-issue/(?P<id>\d+)/edit/people$', views.special_issue_edit_members, name="special_issue_edit_members"),
    re_path(r'^special-issue/(?P<id>\d+)/edit/news$', views.special_issue_edit_news, name="special_issue_edit_news"),
    re_path(r'^special-issue/(?P<id>\d+)/edit/publications$', views.special_issue_edit_publications, name="special_issue_edit_publications"),
    re_path(r'^special-issue/(?P<id>\d+)/description/$', views.special_issue_desc, name="special_issue_desc"),
    re_path(r'^special-issue/(?P<id>\d+)/people/(?P<role_id>\d+)/$', views.special_issue_members, name="special_issue_members"),
    re_path(r'^special-issue/(?P<id>\d+)/creation/$', views.special_issue_members, name="special_issue_members"),
    re_path(r'^special-issue/(?P<id>\d+)/schedule/$', views.special_issue_schedule, name="special_issue_schedule"),
    re_path(r'^special-issue/(?P<id>\d+)/schedule/(?P<program_id>\d+)/remove$', views.event_schedule_remove, name="special_issue_schedule_remove"),
    re_path(r'^special-issue/(?P<id>\d+)/schedule/(?P<schedule_id>\d+)/edit/$', views.schedule_edit, name="special_issue_schedule_edit"),
    re_path(r'^special-issue/(?P<id>\d+)/schedule/creation$', views.schedule_creation, name="special_issue_schedule_creation"),
    re_path(r'^special-issue/(?P<id>\d+)/associated-events/$', views.special_issue_associated_events, name="special_issue_associated_events"),
    re_path(r'^special-issue/(?P<id>\d+)/publications/$', views.special_issue_publications, name="special_issue_publications"),
    re_path(r'^special-issue/(?P<id>\d+)/publication/creation/$', views.publication_creation, name="issue_publication_creation"),
    re_path(r'^special-issue/(?P<id>\d+)/publication/(?P<pub_id>\d+)/edit/$', views.publication_edit, name="publication_edit"),
    re_path(r'^special-issue/(?P<id>\d+)/publication/(?P<pub_id>\d+)/remove/$', views.publication_remove, name="publication_remove"),
    re_path(r'^special-issue/(?P<id>\d+)/associated-events/creation$', views.event_relation_creation, name="special_issue_relation_creation"),
    re_path(r'^special-issue/(?P<id>\d+)/associated-events/(?P<relation_id>\d+)/remove$', views.event_relation_remove, name="special_issue_relation_remove"),
    # re_path(r'^special-issue/(?P<id>\d+)/associated-events/(?P<relation_id>\d+)/edit$', views.event_relation_edit, name="special_issue_relation_edit"),
    re_path(r'^special-issue/(?P<id>\d+)/people/select/$', views.profile_select, name="special_issue_profile_select"),
    re_path(r'^special-issue/(?P<id>\d+)/people/(?P<member_id>\d+)/remove$', views.event_member_remove, name="special_issue_member_remove"),
    re_path(r'^special-issue/(?P<id>\d+)/people/(?P<member_id>\d+)/edit/$', views.profile_edit, name="special_issue_profile_edit"),
    re_path(r'^special-issue/(?P<id>\d+)/news/creation/$', views.news_creation, name="special_issue_news_creation"),
    re_path(r'^special-issue/(?P<id>\d+)/news/(?P<news_id>\d+)/edit/$', views.news_edit, name="special_issue_news_edit"),
    re_path(r'^special-issue/(?P<id>\d+)/news/(?P<news_id>\d+)/remove$', views.event_news_remove, name="special_issue_news_remove"),
    # Role urls
    re_path(r'^role/creation/$', views.role_creation, name="role_creation"),
    re_path(r'^event-proposal/creation/$', views.event_proposal_creation, name="event_proposal_creation"),
    re_path(r'^event-proposal/list/$', views.event_proposal_list, name="event_proposal_list"),
    re_path(r'^event-proposal/(?P<id>\d+)/detail/$', views.event_proposal_detail, name="event_proposal_detail"),
    re_path(r'^event-proposal/(?P<id>\d+)/confirm/$', views.event_proposal_confirm, name="event_proposal_confirm"),
    # Publication urls
    re_path(r'^publication/creation/$', views.publication_creation, name="publication_creation"),
    re_path(r'^publication/list/$', views.publication_list, name="publication_list"),
    re_path(r'^publication/(?P<id>\d+)/detail/$', views.publication_detail, name="publication_detail"),
    re_path(r'^publication/(?P<pub_id>\d+)/edit/$', views.publication_edit, name="publication_edit"),
    re_path(r'^publication/(?P<pub_id>\d+)/remove/$', views.publication_remove, name="publication_remove"),
    # Schedule event urls
    # url(r'^schedule/creation/(?P<id>\d+)/$', views.schedule_creation, name="schedule_creation"),
    # url(r'^schedule/creation/(?P<workshop_id>\d+)/(?P<event_id>\d+)/subevent$', views.subevent_creation, name="subevent_creation"),
    # url(r'^schedule/edit/(?P<id>\d+)/$', views.schedule_edit, name="schedule_edit"),
]
